Add I18N Considerations section
w3c/secure-payment-confirmation pull request #232
Opened 2023-03-07 18:23 UTC by ianbjacobs

Seeks to address #205.

Summary of structure of this pull request:

* Add Internationalization Considerations Section.
* Mention there role of locale member (and link to this section from locale definition)
* Point out that locale does not serve same role as language and bidi metadata, and that the W3C community is still working on that issue.
* Following guidance from @aphillips, cover topics for callers of the API in the meantime, namely (1) consistency between locale and any input displayable strings and (2) clean bidi with reference to an I18N WG document.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/232.html" title="Last updated on Mar 8, 2023, 3:49 PM UTC (e52aff5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/232/1565e06...e52aff5.html" title="Last updated on Mar 8, 2023, 3:49 PM UTC (e52aff5)">Diff</a>

2023-03-08 15:22 UTC, stephenmcgruer requested changes

2023-03-08 15:22 UTC, stephenmcgruer commented on spec.bs
> +93</a>.
```suggestion
they provide as input to the API (e.g., {{PaymentCredentialInstrument/displayName}}).
To track progress on on this topic see
<a href="https://github.com/w3c/secure-payment-confirmation/issues/93">issue 93</a>.
```

Readability nit.

2023-03-08 15:22 UTC, stephenmcgruer commented on spec.bs
> +* Aim for consistency between values of {{SecurePaymentConfirmationRequest/locale}} (when provided) and the language of displayable strings.
```suggestion
* Aim for consistency between values of {{SecurePaymentConfirmationRequest/locale}}
    (when provided) and the language of displayable strings.
```

Readability nit

2023-03-08 15:22 UTC, stephenmcgruer commented on spec.bs
> +* If displayable strings contain or might contain [=bidirectional text=], ensure that they will display correctly without the application needing to process the contents of the string value via the i
```suggestion
* If displayable strings contain or might contain [=bidirectional text=], ensure
    that they will display correctly without the application needing to process
    the contents of the string value via the insertion of Unicode bidirectional
    controls. For more information see [How to use Unicode controls for bidi
    text](https://www.w3.org/International/questions/qa-bidi-unicode-controls).
```

Readability nit

2023-03-08 15:55 UTC, ianbjacobs commented on spec.bs
> +        text: bidirectional text; url: def_bidirectional_text
Compiles without the metadata; yay!

2023-03-08 16:01 UTC, ianbjacobs commented on spec.bs
> +93</a>.
I think I have done this.

2023-03-08 16:01 UTC, ianbjacobs commented on spec.bs
> +* Aim for consistency between values of {{SecurePaymentConfirmationRequest/locale}} (when provided) and the language of displayable strings.
I think I have done this.

2023-03-08 16:01 UTC, ianbjacobs commented on spec.bs
> +* If displayable strings contain or might contain [=bidirectional text=], ensure that they will display correctly without the application needing to process the contents of the string value via the i
I think I have done this.

2023-03-08 16:14 UTC, aphillips commented on spec.bs
>  spec: i18n-glossary; urlPrefix: https://w3c.github.io/i18n-glossary/
Note that i18n-glossary is in the TR space as https://www.w3.org/TR/i18n-glossary and this probably should be your URL here.

2023-03-08 16:38 UTC, aphillips requested changes
Wording suggestion for the locale member, otherwise looking good to me.

2023-03-08 16:38 UTC, aphillips commented on spec.bs
> +Callers of the API may express preferences for localized transaction
Perhaps:

> Callers of the API _should_ express the desired [=locale=] of any dialog experiences in the transaction as well as the localization of any returned display strings via the {{SecurePaymentConfirmationRequest/locale}} member. In general this member should match the localization of the page where the request originates (such as by querying the `lang` attribute of the button triggering the request).

2023-03-08 16:54 UTC, merged

2023-03-08 16:55 UTC, ianbjacobs commented
Thanks all!

2023-03-16 14:57 UTC, ianbjacobs commented
Thank you, @aphillips. I'll work on this early next week.